name = "BaselinePCA"
uuid = "a73da3dd-b873-4b40-ac53-8f4ca87a2bc3"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"

[weakdeps]
Foresight = "c6e1034d-1844-4b96-abf2-c5824a5aa8c3"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExt = ["Makie", "Foresight"]

[compat]
julia = "1.6"
